---
- hosts: localhost
  become: true

  tasks:
  - name: create docker image using war file
    command: docker image build -t edureka_demo:latest .
    args:
      chdir: /opt/playbooks
      
  - name: create tag to image
    command: docker image tag edureka_demo:latest juliannonso/edureka_demo:latest
    
  - name: push image on to docker
    command: docker image push juliannonso/edureka_demo:latest
    
  - name: remove docker image from ansible server
    command: docker image rm edureka_demo:latest juliannonso/edureka_demo:latest
    ignore_errors: yes
