apiVersion: v1
kind: Service
metadata:
  name: edureka-service
  labels:
    app: edureka-devops-project
spec:
  selector:
    app: edureka-devops-project
    type: LoadBalancer # NodePort  ## you can use  Loadbalncer if working on EKS cluster
    ports:
      - port: 8080  # Virtual LB port, you can define any port of your choice
        nodePort: 32200   ## range between 30,000 to 32,767
