apiVersion: apps/v1 # for version before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: edureka-deployment
spec:
  selector:
    matchLabels:
      app: edureka-devops-project
  replicas: 2 #tells deployment to run 2 pods matching the template
  strategy:
    type: RollingUpadate
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: edureka-devops-project
    spec:
      containers:
      - name: edureka-devops-project
        image: juliannonso/edureka_demo:latest
        imagePullPolicy: always
        ports:
        - containerPort: 8080
